Fix for rotation
taranisag/react-native-compare-slider pull request #13
Opened 2021-07-07 14:06 UTC by DenysMoro

2021-07-07 14:08 UTC, aviklai requested changes
@DenysMoro I think we should keep package-lock.json:
https://stackoverflow.com/questions/44206782/do-i-commit-the-package-lock-json-file-created-by-npm-5

2021-07-07 14:13 UTC, DenysMoro commented
@aviklai reverted back

2021-07-07 14:47 UTC, dinataranis commented on examples/screens/Images/Images.tsx
> +  const [size, setSize] = useState({ width, height: width / 2 });
@DenysMoro can you please explain why do we use `height: width / 2` ? 
I think we need to do something like `{width: 100%, height: 'auto'}` (responsive resizing)

2021-07-07 15:16 UTC, aviklai approved these changes

2021-07-08 07:02 UTC, antonazaides approved these changes

2021-07-08 09:33 UTC, aviklai commented on examples/screens/Images/Images.tsx
> +  const [size, setSize] = useState({ width, height: width / 2 });
@DenysMoro ?

2021-07-08 11:03 UTC, merged